=== hust-arms/ARMsAUV/armsauv_sim/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>
<!ATTLIST UWSimScene xmlns:xacro CDATA #IMPLIED>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?,enablePhysics?,gravity?,physicsFrequency?,physicsSubSteps?, physicsSolver?,showTrajectory*,lightRate?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,scaleFactor?,virtualCamera*, structuredLightProjector*, rangeSensor*, objectPicker*, imu*, pressureSensor*, gpsSensor*, dvlSensor*, virtualRangeImage*,multibeamSensor*, simulatedDevices?, echo*, ForceSensor*, DredgeTool*)>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?,fovy?, parameters?, showpath?,grayscale?,std?)>
<!ELEMENT virtualRangeImage (name,relativeTo,resw?,resh?,position?,orientation?,frameId?,fovy?,parameters?)>
<!ELEMENT structuredLightProjector (name,relativeTo,fov,image_name,laser?,position?,orientation?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT objectPicker (name,relativeTo,range,position?,orientation?)>
<!ELEMENT imu (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT pressureSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT gpsSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT dvlSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT multibeamSensor (name,relativeTo,visible?,position?,orientation?, initAngle,finalAngle, angleIncr,range)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,scaleFactor?,offsetp?,offsetr?,physics?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (WorldToROSTF*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?, (ImuToROSImu*)?, (PressureSensorToROS*)?, (GPSSensorToROS*)?, (DVLSensorToROS*)?, (RangeImageSensorToROSImage*)?,(multibeamSensorToLaserScan*)?, (SimulatedDeviceROS*)?,(contactSensorToROS*)?,(echoROS*)?,(ForceSensorROS*)?,(ROSPointCloudLoader*)?,(RangeCameraToPCL*)?) >

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT scaleFactor (x,y,z)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT std (#PCDATA)>
<!ELEMENT target (#PCDATA)>


<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>
<!ELEMENT showTrajectory (target,color?,lineStyle?,timeWindow?)>
<!ELEMENT lineStyle (#PCDATA)>
<!ELEMENT timeWindow (#PCDATA)>
<!ELEMENT enablePhysics (#PCDATA)>
<!ELEMENT physicsFrequency (#PCDATA)>
<!ELEMENT physicsSubSteps (#PCDATA)>
<!ELEMENT physicsSolver (#PCDATA)>
<!ELEMENT gravity (x,y,z)>
<!ELEMENT lightRate (#PCDATA)>

<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ATTLIST virtualRangeImage underwaterParticles (true|false) #IMPLIED>
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>
<!ELEMENT fovy (#PCDATA)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>
<!ELEMENT showpath (#PCDATA)>
<!ELEMENT grayscale (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!--elementos structuredLightProjector -->
<!ELEMENT image_name (#PCDATA)>
<!ELEMENT laser (#PCDATA)>

<!--elementos multibeamSensor -->
<!ATTLIST multibeamSensor underwaterParticles (true|false) #IMPLIED>
<!ELEMENT initAngle (#PCDATA)>
<!ELEMENT finalAngle (#PCDATA)>
<!ELEMENT angleIncr (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?)>
<!ELEMENT WorldToROSTF  (rootName, enableObjects?, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?,depth?)>
<!ELEMENT RangeImageSensorToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,blackWhite?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>
<!ELEMENT ImuToROSImu (name, topic, rate?)>
<!ELEMENT PressureSensorToROS (name, topic, rate?)>
<!ELEMENT GPSSensorToROS (name, topic, rate?)>
<!ELEMENT DVLSensorToROS (name, topic, rate?)>
<!ELEMENT multibeamSensorToLaserScan (name, topic, rate?)>
<!ELEMENT contactSensorToROS (name, topic, rate?)>
<!ELEMENT ROSPointCloudLoader (topic)>
<!ATTLIST ROSPointCloudLoader delLastPCD (true|false) #IMPLIED>
<!ELEMENT RangeCameraToPCL (cameraName, topic, rate?)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT blackWhite (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT rootName (#PCDATA)>
<!ELEMENT enableObjects (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!-- elementos physics -->
<!ATTLIST object buried CDATA #IMPLIED>
<!ELEMENT physics (mass?,inertia?,collisionShapeType?,collisionShape?,linearDamping?,angularDamping?,isKinematic? , minLinearLimit?, maxLinearLimit?,minAngularLimit?,maxAngularLimit?)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT inertia (x,y,z)>
<!ELEMENT collisionShapeType (#PCDATA)>
<!ELEMENT collisionShape (#PCDATA)>
<!ELEMENT linearDamping (#PCDATA)>
<!ELEMENT angularDamping (#PCDATA)>
<!ELEMENT minLinearLimit (x,y,z)>
<!ELEMENT maxLinearLimit (x,y,z)>
<!ELEMENT isKinematic (#PCDATA)>
<!ELEMENT minAngularLimit (x,y,z)>
<!ELEMENT maxAngularLimit (x,y,z)>


<!-- simulatedDevices -->
<!ELEMENT simulatedDevices (
echo*
)>
<!ELEMENT SimulatedDeviceROS (
echoROS?
)>

<!ELEMENT echo (name, info )>
<!ELEMENT echoROS (name, topic, rate?)>

<!ELEMENT ForceSensor (name, target, offsetp, offsetr)>
<!ELEMENT ForceSensorROS (name, topic, rate?)>

<!ELEMENT DredgeTool (name, target, offsetp, offsetr)>

=== hust-arms/ARMsAUV/armsauv_sim/scenes/block_cirs.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
<oceanState>
  <windx>0.04</windx>
  <windy>0.04</windy>
  <windSpeed>12</windSpeed>
  <depth>1000</depth>
  <reflectionDamping>0.35</reflectionDamping>
  <waveScale>1e-7</waveScale>
  <isNotChoppy>0</isNotChoppy>
  <choppyFactor>2.5</choppyFactor>
  <crestFoamHeight>2.2</crestFoamHeight>
  <oceanSurfaceHeight>0</oceanSurfaceHeight>
  <fog>
    <density>0.1</density>
    <color>
      <r>0.0</r>
      <g>0.05</g>
      <b>0.3</b>
    </color>
  </fog>
  <color>
    <r>0.0</r>
    <g>0.05</g>
    <b>0.3</b>
  </color>
  <attenuation>
    <r>0.015</r>
    <g>0.0075</g>
    <b>0.005</b>
  </attenuation>
</oceanState>
  
<simParams>
  <disableShaders>0</disableShaders>
  <resw>800</resw>
  <resh>600</resh>
  <offsetp>
    <x>0</x>
    <y>0</y>
    <z>0</z>
  </offsetp>
  <offsetr>
    <x>3.14</x>
    <y>0</y>
    <z>-1.57</z>
  </offsetr>
  <enablePhysics>1</enablePhysics>
  <showTrajectory>
    <target>block</target>
  </showTrajectory>
</simParams>

<camera>
  <freeMotion>1</freeMotion>
  <objectToTrack>block/base_link</objectToTrack>
  <fov>60</fov>
  <aspectRatio>1.33</aspectRatio>
  <near>0.1</near>
  <far>10000</far>
  <position>
    <x>-5</x>
    <y>-5</y>
    <z>8</z>
  </position>
  <lookAt>
    <x>0</x>
    <y>0</y>
    <z>0</z>
  </lookAt>
</camera>

<vehicle>
  <name>block</name> 
  <file>/opt/ros/melodic/share/urdf_tutorial/urdf/05-visual.urdf</file>
  
  <position>
    <x>2</x>
    <y>0</y>
    <z>2</z>
  </position>
  <orientation>
    <r>0</r>
    <p>0</p>
    <y>0</y>
  </orientation>

</vehicle>


<object>
  <name>terrain</name>
  <file>terrain/CIRS/cirs_trident.osg</file>
  <!-- <file>/opt/ros/melodic/share/uuv_gazebo_worlds/models/ocean/ocean.sdf</file> -->
  <position>
    <x>0</x>
    <y>0</y>
    <z>0</z>
  </position>
  <orientation>
    <r>0</r>
    <p>0</p>
    <y>0</y>
  </orientation>
  <offsetp>
    <x>-1.5</x>
    <y>-3.0</y>
    <z>0</z>
  </offsetp>
  <offsetr>
    <x>3.1415</x>
    <y>0</y>
    <z>-1.57</z>
  </offsetr>
  <physics>
    <mass>0</mass>
    <collisionShapeType>trimesh</collisionShapeType>
  </physics>
</object>

<object>
  <name>blackbox</name>
  <file>objects/blackbox_uib_trimesh.osg</file>
  <position>
    <x>0</x>
    <y>0</y>
    <z>4.7</z>
  </position>
  <orientation>
    <r>0</r>
    <p>3.1415</p>
    <y>0</y>
  </orientation>
  <physics>
    <mass>15</mass>
    <inertia>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </inertia>
    <collisionShapeType>box</collisionShapeType>
  </physics>
</object>

</UWSimScene>
